base_url = "https://ribeirovidal.com/"
title = "MRV"
description = "Matheus Ribeiro Vidal - Personal Website"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
last_update_to_site = "2025-11-07T16:06:32"
toc = true
use_cdn = true
favicon = "/icons/caja_acerola.ico"
meta_image_url = "https://ribeirovidal.com/icons/meta_banner2.png"
meta_image_url_test = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1024px-React-icon.svg.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/not-matthias/apollo/tree/main/content/"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 9 },
]

socials = [
	{ name = "linkedin", url = "https://www.linkedin.com/in/matheusribeirovidal/", icon = "linkedin"},
	{ name = "email", url = "mailto:matheus@ribeirovidal.com", icon = "email"},
    { name = "instagram", url = "https://www.instagram.com/theusvid/", icon = "instagram" },
	{ name = "orcid", url = "https://orcid.org/0009-0009-2651-461X", icon = "orcid" },
    { name = "github", url = "https://github.com/ChurroGelato", icon = "github" },
	{ name = "itch.io", url = "https://churrogelato.itch.io/", icon = "itchio" },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "13495561"
host = "goatcounter.com" # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://api-gateway.umami.dev/
